version: "3.3"
services:
  app:
    build: .
    ports:
      - 8080:8080
      
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

volumes:
  db-data:

networks:
  default:
    name: ict_net
    external: true